server:
  port: 9600


skv:
  type: redis
  uri: redis://localhost/0

slardar:
  token:
    type: jwt
  login:
    concurrent-policy: mutex
    captcha-enabled: false


spring:
  application:
    name: slardar-demo
swagger:
  enabled: true
