server:
  port: 9600


skv:
  type: redis
  uri: redis://localhost/0


slardar:
  sso-server:
    ctx-path: /sso
  token:
    type: jwt
  login:
    post-only: false
    captcha-enabled: false
  ignores: /login,/sso-login


spring:
  application:
    name: slardar-demo
swagger:
  enabled: true
