server:
  port: 9601

slardar:
  key-store:
    type: redis # token 存储使用内存模式 仅限演示
    uri: redis://localhost/0
  login:
    post-only: false
    captcha-enabled: false
    encrypt:
      enabled: false
      mode: mystical #使用自定义的加解密实现
    max-attempts-before-locked: 30 # 最大尝试次数
    failed-lock-duration: 2m   # 失败锁定时间
    login-failed-http-status: 200 # 登录失败返回的状态码200 默认是 500
  ignores: /login,/sso-login,/mfa-login
  # 验证码相关配置
  captcha:
    code-type: random
    code-length: 6
    gif: true
    width: 200
  cluster: true # 是否集群模式

spring:
  #  main:
  #    allow-bean-definition-overriding: true
  application:
    name: slardar-server-demo

application:
  openapi:
    cors: true