server:
  port: 9600


skv:
  type: redis
  uri: redis://localhost/0


slardar:
#  ldap:
#    url: ldap://124.221.177.135:389
#    base: dc=test,dc=cn
  sso:
    ctx-path: /sso
  token:
    type: jwt
  login:
    post-only: false
    captcha-enabled: false
    encrypt:
      enabled: false
      mode: sm4
  ignores: /login,/sso-login,/mfa-login
  mfa:
    enabled: false
    otp-mode: email
    email:
      host: smtp.163.com
      port: 25
      username: yxfacw@163.com
      password: ZYAHAOPEZGKGLABK



spring:
  application:
    name: slardar-demo
swagger:
  enabled: true
