server:
  port: 9600



skv:
  type: redis
  uri: redis://localhost/0


slardar:
#  ldap:
#    url: ldap://124.221.177.135:389
#    base: dc=test,dc=cn
  sso:
    ctx-path: /sso
  token:
    type: jwt
  login:
    post-only: false
    captcha-enabled: false
    encrypt:
      enabled: false
      mode: sm4
    max-attempts-before-locked: 3 # 最大尝试次数
    failed-lock-duration: 2m   # 失败锁定时间
  ignores: /login,/sso-login,/mfa-login
  mfa:
    enabled: false
    otp-mode: email
    email:
      host: smtp.163.com
      port: 25
      username: yxfacw@163.com
      password: ZYAHAOPEZGKGLABK



spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: slardar-server-demo
swagger:
  enabled: true
