server:
  port: 9700

slardar:
  token:
    type: jwt
  key-store:
    type: mapdb
  login:
    post-only: false
    captcha-enabled: false
    max-attempts-before-locked: 3 # 最大尝试次数
    failed-lock-duration: 2m   # 失败锁定时间
    login-failed-http-status: 200 # 登录失败返回的状态码200 默认是 500
  ignores: /licenseManager,/login,/sso-login,/mfa-login



spring:
  application:
    name: slardar-license-demo
swagger:
  enabled: true
